on:
  push:
    paths: 
      - 'example/*.md'
jobs:
  translate2en:
    runs-on: ubuntu-latest
    name: A job to test this action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Translate
        uses: ./
        with:
          input_file: "example/test_fr.md"
          output_file: "example/test_en.md"
          output_lang: "en"
          deepl_free_token: "${{ secrets.TOKEN }}"
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: example/test_en.md